name: Publish Package

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'   # Trigger on version tags like v1.0.0

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    environment: npm-publish

    permissions:
      contents: read         # Needed to checkout code
      id-token: write        # Needed for OIDC
      packages: write        # Needed to publish packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Authenticate with npm using OIDC
        run: |
          # Request an OIDC token and authenticate to npm registry
          echo "//registry.npmjs.org/:_authToken=\${{ steps.oidc.outputs.npm_token }}" > ~/.npmrc
        id: oidc

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --access public
